-- ==========================================================
-- PROYECTO: BYCAR
-- DESCRIPCIÓN: Creación de la tabla USUARIOS con restricciones DDL
-- ==========================================================

DROP TABLE USUARIOS CASCADE CONSTRAINTS;

CREATE TABLE USUARIOS (
    ID_USU NUMBER,
    NOMBRE_USU VARCHAR2(100 BYTE) NOT NULL,
    APELLIDO_USU VARCHAR2(100 BYTE) NOT NULL,
    CORREO_USU VARCHAR2(150 BYTE) NOT NULL UNIQUE,
    CONTRASENA_USU VARCHAR2(255 BYTE) NOT NULL,
    PERFIL_ID_PER NUMBER NOT NULL,
    FECHA_CREACION DATE DEFAULT SYSDATE,

    CONSTRAINT PK_USUARIOS
        PRIMARY KEY(ID_USU),

    CONSTRAINT FK_USUARIOS_PERFIL
        FOREIGN KEY(PERFIL_ID_PER)
        REFERENCES PERFILES (ID_PER)
        ON DELETE CASCADE
) TABLESPACE TS_BYCAR;

COMMIT;
